### ISSUE TITLE
Fails with perls < 5.16

### ISSUE THREAD

**Issue by andk** [mcmillhj/Keyword-With#1]
As per subject. Best illustrated with the matrix: 

http://matrix.cpantesters.org/?dist=Keyword-With%200.001

Sample fail report:

http://www.cpantesters.org/cpan/report/5c930056-383a-11e6-bce4-3fd56608a794

Diagnostics: 

Feature "current_sub" is not supported by Perl 5.14.4 at t/01-with.t line 6.

If this is intentional, it would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Let me know if you need further information.

HTH&&Thanks,

**Comment by mcmillhj** [comment]
Thank you for the report, I changed the minimum Perl to 5.16 in my TravisCI config, but forgot about the Makefile.PL. In looking at this more, there is no reason earlier Perls' couldn't make use of this module so I am going to remove my use of current_sub in the testfile and target Perl 5.10.

**Comment by mcmillhj** [comment]
Fixed by 3a7b0dc1b791117eaf6cb1633178a8d6c1885f4c
